### ISSUE TITLE
Feature Request: Display Most Recent Projects

### ISSUE THREAD

**Issue by ankitbisen28** [ankitbisen28/Atelier#10]
#### Description
Create a feature that displays the most recent projects on the platform. This will help users to quickly access the latest projects posted by other users.

#### Requirements
1. **Most Recent Projects Display**:
    - Implement a section on the homepage or a dedicated page that lists the most recent projects.
    - Display key details of each project such as title, description, budget, deadline, and category.
    - Provide a link to view more details about each project.

2. **Backend Implementation**:
    - Implement a backend endpoint to fetch the most recent projects from the database.
    - Ensure the endpoint returns projects sorted by the creation date in descending order.

#### Acceptance Criteria
- A section or page displays the most recent projects.
- Projects are sorted by the most recently created.
- Each project shows key details and a link to view more details.
- The interface is responsive and works well on various devices.

#### Additional Information
- Ensure the component is responsive and accessible.
- Provide clear error messages for any issues in fetching or displaying the projects.

#### Mockups / Examples
Provide any mockups or examples of the desired component if available.

#### Technical Requirements
- Ensure compatibility with the existing tech stack of the project.
- Utilize efficient algorithms to handle fetching and sorting of recent projects without significant performance degradation.

#### Mongoose Schema for Reference
```javascript
const mongoose = require('mongoose');

const projectSchema = mongoose.Schema({
    "title": String,
    "description": String,
    "requirements": String,
    "budget": Number,
    "deadline": Date,
    "consumerId": String, // Reference to the user who posted the project
    "category": String,
    "images": [
        {
            "url": String, // URL of the image stored in an external service
            "description": String, // Optional description of the image
            "uploadedAt": Date // Timestamp when the image was uploaded
        }
    ],
    "bids": [
        {
            "bidderId": String, // Reference to the user who placed the bid
            "amount": Number,
            "message": String,
            "createdAt": Date
        }
    ],
    "selectedBidder": String, // Reference to the selected bidder (if any)
    "status": String, // "open", "closed", "in progress", "completed"
    "createdAt": Date,
    "updatedAt": Date
});

projectSchema.virtual('id').get(function () {
    return this._id.toHexString();
});

projectSchema.set('toJSON', {
    virtuals: true,
});

module.exports = mongoose.model('project', projectSchema);
```

#### Steps to Get Most Recent Projects using Node.js

1. **Define the Backend Endpoint**:
    - Create a new route in your Node.js application to handle requests for the most recent projects.

    ```javascript
    const express = require('express');
    const router = express.Router();
    const Project = require('../models/project');

    router.get('/projects/recent', async (req, res) => {
        try {
            const recentProjects = await Project.find().sort({ createdAt: -1 }).limit(10);
            res.status(200).json(recentProjects);
        } catch (error) {
            res.status(500).json({ message: 'Failed to fetch recent projects', error });
        }
    });

    module.exports = router;
    ```

2. **Integrate and Test**:
    - Ensure the endpoint and frontend component are integrated correctly.
    - Test the functionality thoroughly to ensure recent projects are displayed as expected.

#### Tasks
- [ ] Implement the backend endpoint to fetch the most recent projects.
- [ ] Create the frontend component to display the most recent projects.
- [ ] Integrate the backend and frontend components.
- [ ] Test the feature thoroughly.
