### ISSUE TITLE
Implement "Forget Password" Feature Using Nodemailer

### ISSUE THREAD

**Issue by ankitbisen28** [ankitbisen28/Atelier#5]
**Description:**

We need to implement a "Forget Password" feature that allows users to reset their passwords if they forget them. This feature should send an email to the user's registered email address with a password reset link. We will use Nodemailer to set up an SMTP server for sending the emails.

**Tasks:**

1. **Create Password Reset API Endpoint:**
   - [ ] Create an API endpoint `/api/auth/forgot-password` to handle password reset requests.
   - [ ] Validate the email address provided by the user.
   - [ ] Generate a secure token and save it to the database with an expiration time.

2. **Setup Nodemailer:**
   - [ ] Install Nodemailer: `npm install nodemailer`
   - [ ] Configure Nodemailer with SMTP settings (e.g., using Gmail, Mailgun, or any other SMTP service).

3. **Send Password Reset Email:**
   - [ ] Create an email template for the password reset email.
   - [ ] Use Nodemailer to send the email with the password reset link, including the secure token in the link.

4. **Create Password Reset Page:**
   - [ ] Create a front-end page where users can enter a new password.
   - [ ] Validate the token and ensure it has not expired.
   - [ ] Update the user's password in the database.

5. **Security Considerations:**
   - [ ] Ensure the token is securely generated and stored.
   - [ ] Implement rate limiting on the password reset endpoint to prevent abuse.
   - [ ] Ensure the reset link expires after a certain period (e.g., 1 hour).

**Additional Information:**

- **SMTP Server Configuration:**
  - Example configuration for Nodemailer:
    ```javascript
    const nodemailer = require('nodemailer');

    let transporter = nodemailer.createTransport({
      host: 'smtp.example.com',
      port: 587,
      secure: false, // true for 465, false for other ports
      auth: {
        user: 'your-email@example.com', // generated ethereal user
        pass: 'your-email-password', // generated ethereal password
      },
    });

    let mailOptions = {
      from: '"Your App Name" <your-email@example.com>', // sender address
      to: 'user@example.com', // list of receivers
      subject: 'Password Reset', // Subject line
      text: 'Please click the link below to reset your password.', // plain text body
      html: '<b>Please click the link below to reset your password:</b>', // html body
    };

    transporter.sendMail(mailOptions, (error, info) => {
      if (error) {
        return console.log(error);
      }
      console.log('Message sent: %s', info.messageId);
      console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
    });
    ```

- **Expiration Handling:**
  - Save the token in the database with an expiration time.
  - Check the expiration time when the user accesses the password reset link.

**References:**
- [Nodemailer Documentation](https://nodemailer.com/about/)

**Labels:**
- enhancement
- backend
- front-end
- security

---

Please review the tasks and provide any feedback or additional requirements. Once approved, we can start working on this feature.

---
